name: Development Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Xcode Version
      run: sudo xcode-select -s /Applications/Xcode_15.4.app

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      id: setup-java
      with:
        java-version: '8'
        distribution: 'zulu'

    - name: Install Dependencies
      run: |
        brew install ldid wget make
        sudo mkdir -p /usr/local/bin
        sudo ln -sf /opt/homebrew/bin/gmake /usr/local/bin/gmake

    - name: Build Amethyst
      run: |
        JDK_BASE_PATH="${{ steps.setup-java.outputs.path }}"
        export PATH="$JDK_BASE_PATH/bin:$PATH"

        make clean \
          JAVA_HOME="$JDK_BASE_PATH" \
          BOOTJDK="$JDK_BASE_PATH/bin" || true

        make \
          JAVA_HOME="$JDK_BASE_PATH" \
          BOOTJDK="$JDK_BASE_PATH/bin"

    - name: Upload Finished IPA
      uses: actions/upload-artifact@v4
      with:
        name: Amethyst
        path: artifacts/org.angelauramc.amethyst-*-ios.ipa
